### ISSUE TITLE
keep going

### ISSUE THREAD

**Issue by Caplost** [SawyerHood/draw-a-ui#1]
This is a very disruptive thing, and I hope it can disrupt this industry.

**Comment by TheRealPlagiariser** [comment]
I have to mention this might still be technically paid, although at a much lower cost with the usage of OpenAI. As much as I like OpenAI and gpt models, it might be the case that history repeats itself as we've seen happen everytime in the past, and the paywall just becomes higher and higher until it's no longer affordable.
