### ISSUE TITLE
Error on localhost

### ISSUE THREAD

**Issue by Maryjane1337** [SawyerHood/draw-a-ui#12]
Hi, why i get the error: Error from open ai: [object Object] ? thanks <3

**Comment by Maryjane1337** [comment]
actually yeah, i have a premium acc

**Comment by Adi-111** [comment]
have you entered your api key correctly

**Comment by SawyerHood** [comment]
I’m assuming this is similar to another issue, you have to pay OpenAI a dollar to use the gpt-4 vision api https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo
