### ISSUE TITLE
Model Not Found

### ISSUE THREAD

**Issue by jasperfurniss** [SawyerHood/draw-a-ui#14]
Error I'm getting when i hit the "Make Real" button:

Error from open ai: {"message":"The model `gpt-4-vision-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.","type":"invalid_request_error","param":null,"code":"model_not_found"}

I have access to GPT-4, and have been a pro subscriber for a few months. 

Any ideas?

**Comment by statulr** [comment]
Do you have API Access?

**Comment by statulr** [comment]
Have you added your api key in the env?

**Comment by jasperfurniss** [comment]
Yes to both. @statulr

**Comment by SawyerHood** [comment]
@jasperfurniss have you paid open ai $1 yet? https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4

**Comment by jasperfurniss** [comment]
🤦  Omg. Thank you, @SawyerHood . 

That was not very easy to find for some reason in their UI.

**Comment by bryanrigsby** [comment]
> @jasperfurniss have you paid open ai $1 yet? https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4

is this $1 above the ChatGPT plus subscription?
