### ISSUE TITLE
How can stars grow so fast 😳

### ISSUE THREAD

**Issue by Dalufishe** [SawyerHood/draw-a-ui#16]

**Comment by Vilhelm-Ian** [comment]
I think it was shown in a youtube video and probably word of mouth

**Comment by arsandydev** [comment]
bot

**Comment by umarmnaq** [comment]
https://star-history.com/#SawyerHood/draw-a-ui&Date

**Comment by PrivateGER** [comment]
All these weird AI projects are botted. Heavily. Seriously, just look at their stargazer page.

**Comment by PrivateGER** [comment]
> > All these weird AI projects are botted. Heavily. Seriously, just look at their stargazer page.
> 
> Why would anyone bot a project that doesn't have a sponsor link or anything to earn money with? Stars aren't worth anything else, so that would be pointless.

Simple, so they can put it on their CV.

**Comment by SawyerHood** [comment]
My original tweet blew up a bit and then it looks like from analytics other people have shared the repo on other channels (linkedin). I think that got it to trending and now that it is on trending it is just kinda growing by itself. https://x.com/sawyerhood/status/1721717738941698389?s=20
