### ISSUE TITLE
Error from open ai: "slow down"

### ISSUE THREAD

**Issue by QBlockQ** [SawyerHood/draw-a-ui#27]
Why I receive this error, am I  making requests to the API too quickly, exceeding the rate limits?

**Comment by Chandima1990** [comment]
Probably yes. But this happened to me on first few times. But then it did not occur.

**Comment by SawyerHood** [comment]
See this issue: https://github.com/SawyerHood/draw-a-ui/issues/8

I think this is open ai doing rate limiting to mitigate DDOS attacks.
