### ISSUE TITLE
error :./tldraw.css is not exported from package @tldraw/tldraw

### ISSUE THREAD

**Issue by xurenlu** [SawyerHood/draw-a-ui#33]
https://nextjs.org/docs/messages/module-not-found
 ⨯ ./app/page.tsx:4:0
Module not found: Package path ./tldraw.css is not exported from package /Users/xurenlu/Sites/draw-a-ui/node_modules/@tldraw/tldraw (see exports field in /Users/xurenlu/Sites/draw-a-ui/node_modules/@tldraw/tldraw/package.json)
  2 |
  3 | import dynamic from "next/dynamic";
> 4 | import "@tldraw/tldraw/tldraw.css";
  5 | import { useEditor } from "@tldraw/tldraw";
  6 | import { getSvgAsImage } from "@/lib/getSvgAsImage";
  7 | import { blobToBase64 } from "@/lib/blobToBase64";

**Comment by skcary** [comment]
> https://nextjs.org/docs/messages/module-not-found ⨯ ./app/page.tsx:4:0 Module not found: Package path ./tldraw.css is not exported from package /Users/xurenlu/Sites/draw-a-ui/node_modules/@tldraw/tldraw (see exports field in /Users/xurenlu/Sites/draw-a-ui/node_modules/@tldraw/tldraw/package.json) 2 | 3 | import dynamic from "next/dynamic";
> 
> > 4 | import "@tldraw/tldraw/tldraw.css";
> > 5 | import { useEditor } from "@tldraw/tldraw";
> > 6 | import { getSvgAsImage } from "@/lib/getSvgAsImage";
> > 7 | import { blobToBase64 } from "@/lib/blobToBase64";

"@tldraw/tldraw": "2.0.0-alpha.17",

**Comment by skcary** [comment]
@xurenlu  "@tldraw/tldraw": "2.0.0-alpha.17",

**Comment by chunsenye** [comment]
the same with #3

**Comment by Lol4ikS** [comment]
1

**Comment by AndySSSSSS** [comment]
find this "@tldraw/tldraw": "^2.0.0-alpha.17" in package.json
delete the ^
npm install
bingo

**Comment by SawyerHood** [comment]
Fixed here https://github.com/SawyerHood/draw-a-ui/commit/36384b82f7bad0aaa003877fa28571cabfeef6bb
