### ISSUE TITLE
I get an empty response

### ISSUE THREAD

**Issue by daribock** [SawyerHood/draw-a-ui#49]
I get an empty response.

Console.log of `resp` and `resp.json`:
![image](https://github.com/SawyerHood/draw-a-ui/assets/57658125/1824ac49-6547-451d-9cc5-f265d0a08df1)

Network tab:
![image](https://github.com/SawyerHood/draw-a-ui/assets/57658125/be8c78f9-0ece-450f-a034-5e0f8a4aaab9)

![image](https://github.com/SawyerHood/draw-a-ui/assets/57658125/6798101a-cea8-4c36-b835-671d381f4acc)

The API key is correct and the request works but I don't get any response does anyone know why? :(

**Comment by gepeng123** [comment]
Me too.  Have you found the reason yet

**Comment by daribock** [comment]
> Me too. Have you found the reason yet

No unfortunately not :(

**Comment by HikariSad** [comment]
Me too

**Comment by daribock** [comment]
I tried it out again and it worked. I don't know what changed but it works for me know.
I love the idea of the project and I will definitely use it! Thank you @SawyerHood 🥳
