### ISSUE TITLE
我应该如何将它安装在服务器，让我打开网页使用？

### ISSUE THREAD

**Issue by billowssun** [SawyerHood/draw-a-ui#67]
我应该如何将它安装在服务器，让我打开网页使用？

**Comment by chunsenye** [comment]
这是一个next.js的项目
比较简单的办法是部署到[vercel](https://vercel.com)/上，具体怎么部署可以问一下gpt，不会很难
但是提醒一下你得有gpt-4 的API token才能使用自动切图功能哦
