### ISSUE TITLE
Slow down error

### ISSUE THREAD

**Issue by egoran2** [SawyerHood/draw-a-ui#8]
![Screenshot 2023-11-09 172509](https://github.com/SawyerHood/draw-a-ui/assets/144932275/ead087f5-5378-4828-8dee-b83fdb3be1ac)

**Comment by SawyerHood** [comment]
This is an issue with OpenAI right now. They have degraded service:

https://community.openai.com/t/getting-hit-with-429-slow-down-error/482704

**Comment by SawyerHood** [comment]
https://status.openai.com/

**Comment by egoran2** [comment]
still has same error
